insert into car (id, model,brand,years ) values (1,'M', 'Infiniti', 2012);
insert into car (id, model,brand,years ) values (2, 'Elantra', 'Hyundai', 2006);
insert into car (id, model,brand,years ) values (3, 'MR2', 'Toyota', 1985);
insert into car (id, model,brand,years ) values (4, 'Crown Victoria', 'Ford', 2004);
insert into car (id, model,brand,years ) values (5, 'Explorer Sport Trac', 'Ford', 2001);
insert into car (id, model,brand,years ) values (6, 'Avalon', 'Toyota', 2011);
insert into car (id, model,brand,years ) values (7, 'Prius', 'Toyota', 2003);
insert into car (id, model,brand,years ) values (8, 'E-350 Super Duty', 'Ford', 2006);
insert into car (id, model,brand,years ) values (9, 'Spyder', 'Maserati', 2005);
insert into car (id, model,brand,years ) values (10, 'Corvette', 'Chevrolet', 1953);
insert into car (id, model,brand,years ) values (11, 'E-Class', 'Mercedes-Benz', 2012);
insert into car (id, model,brand,years ) values (12, 'CL-Class', 'Mercedes-Benz', 2008);
insert into car (id, model,brand,years ) values (13, 'Sierra Denali', 'GMC', 2006);
insert into car (id, model,brand,years ) values (14, '90', 'Audi', 1993);
insert into car (id, model,brand,years ) values (15, 'Boxster', 'Porsche', 2008);
insert into car (id, model,brand,years ) values (16, 'Shadow', 'Dodge', 1994);
insert into car (id, model,brand,years ) values (17, 'Ram 1500', 'Dodge', 1995);
insert into car (id, model,brand,years ) values (18, 'Impala', 'Chevrolet', 2008);
insert into car (id, model,brand,years ) values (19, 'Econoline E250', 'Ford', 2000);
insert into car (id, model,brand,years ) values (20, 'Escalade ESV', 'Cadillac', 2009);
insert into car (id, model,brand,years ) values (21, 'Swift', 'Suzuki', 2000);
insert into car (id, model,brand,years ) values (22, 'Town Car', 'Lincoln', 1986);
insert into car (id, model,brand,years ) values (23, 'Patriot', 'Jeep', 2010);
insert into car (id, model,brand,years ) values (24, '960', 'Volvo', 1994);
insert into car (id, model,brand,years ) values (25, 'M', 'Infiniti', 2010);
insert into car (id, model,brand,years ) values (26, 'Tribute', 'Mazda', 2001);
insert into car (id, model,brand,years ) values (27, 'Karif', 'Maserati', 1989);
insert into car (id, model,brand,years ) values (28, 'S-Class', 'Mercedes-Benz', 1987);
insert into car (id, model,brand,years ) values (29, 'Mountaineer', 'Mercury', 2000);
insert into car (id, model,brand,years ) values (30, 'Express 2500', 'Chevrolet', 2008);
insert into car (id, model,brand,years ) values (31, 'MR2', 'Toyota', 2004);
insert into car (id, model,brand,years ) values (32, 'Legacy', 'Subaru', 2012);
insert into car (id, model,brand,years ) values (33, 'RAV4', 'Toyota', 2005);
insert into car (id, model,brand,years ) values (34, 'SC', 'Lexus', 2005);
insert into car (id, model,brand,years ) values (35, 'Tracker', 'Geo', 1996);
insert into car (id, model,brand,years ) values (36, 'SL-Class', 'Mercedes-Benz', 1985);
insert into car (id, model,brand,years ) values (37, '2500', 'Ram', 2011);
insert into car (id, model,brand,years ) values (38, 'Cutlass Supreme', 'Oldsmobile', 1996);
insert into car (id, model,brand,years ) values (39, 'SLK-Class', 'Mercedes-Benz', 1998);
insert into car (id, model,brand,years ) values (40, 'California', 'Ferrari', 2010);
insert into car (id, model,brand,years ) values (41, 'Outlander Sport', 'Mitsubishi', 2012);
insert into car (id, model,brand,years ) values (42, 'Esprit', 'Lotus', 1987);
insert into car (id, model,brand,years ) values (43, 'Rally Wagon 2500', 'GMC', 1992);
insert into car (id, model,brand,years ) values (44, 'Land Cruiser', 'Toyota', 2011);
insert into car (id, model,brand,years ) values (45, 'SRX', 'Cadillac', 2009);
insert into car (id, model,brand,years ) values (46, 'ES', 'Lexus', 1993);
insert into car (id, model,brand,years ) values (47, 'Fiero', 'Pontiac', 1988);
insert into car (id, model,brand,years ) values (48, 'Dakota Club', 'Dodge', 1995);
insert into car (id, model,brand,years ) values (49, 'Rally Wagon 1500', 'GMC', 1992);
insert into car (id, model,brand,years ) values (50, 'New Beetle', 'Volkswagen', 2008);
